N4 landing
include-davis/jass-ws24 pull request #16
Opened 2024-04-24 23:55 UTC by michelleyeoh

Finished landing page - still need to route button

2024-04-30 01:53 UTC, amy-ym-yu commented
- Good job on the aesthetics for this one! 
- For things like header, button, etc, we want those all to be editable. If you can just change the text to be a variable like you did with image, this will be ready to merge in!

2024-04-30 01:54 UTC, amy-ym-yu requested changes
- Good job on the aesthetics for this one! 
- For things like header, button, etc, we want those all to be editable. If you can just change the text to be a variable like you did with image, this will be ready to merge in!

2024-05-01 23:55 UTC, michelleyeoh commented
Added button JSON

2024-05-08 23:43 UTC, amy-ym-yu approved these changes

2024-05-08 23:47 UTC, merged